-- =============================================================================
-- ClyvoVet API - DDL do banco de dados (Oracle)
-- =============================================================================
-- Gerado a partir do modelo do Entity Framework Core (AppDbContext), com:
--
--     dotnet ef dbcontext script --project ClyvoVetApi.csproj -o script_bd.sql
--
-- O terminador de bloco "/" foi movido para linha propria, para que o script
-- execute em SQL*Plus, SQLcl e SQL Developer sem edicao manual.
--
-- Ordem de criacao (respeita as dependencias de chave estrangeira):
--     DONOS, FUNCIONARIOS, MEDICAMENTOS
--       -> PETS (FK: DONOS)
--       -> CONSULTAS (FK: PETS, FUNCIONARIOS)
--       -> VACINAS (FK: PETS)
--       -> CONSULTAS_MEDICAMENTOS (FK: CONSULTAS, MEDICAMENTOS)
--
-- Executar:
--     sqlplus usuario/senha@host:1521/servico @script_bd.sql
-- =============================================================================

BEGIN 
EXECUTE IMMEDIATE 'CREATE TABLE 
"DONOS" (
    "dono_id" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    "dono_nome" NVARCHAR2(50) NOT NULL,
    "dono_email" NVARCHAR2(50) NOT NULL,
    "dono_telefone" NVARCHAR2(20) NOT NULL,
    CONSTRAINT "DONOS_PK" PRIMARY KEY ("dono_id")
)';
END;
/

BEGIN 
EXECUTE IMMEDIATE 'CREATE TABLE 
"FUNCIONARIOS" (
    "funcionario_id" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    "funcionario_nome" NVARCHAR2(50) NOT NULL,
    "funcionario_setor" NVARCHAR2(50) NOT NULL,
    "funcionario_cargo" NVARCHAR2(50) NOT NULL,
    "funcionario_email" NVARCHAR2(50) NOT NULL,
    "funcionario_telefone" NVARCHAR2(20) NOT NULL,
    CONSTRAINT "FUNCIONARIOS_PK" PRIMARY KEY ("funcionario_id")
)';
END;
/

BEGIN 
EXECUTE IMMEDIATE 'CREATE TABLE 
"MEDICAMENTOS" (
    "medicamento_id" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    "medicamento_nome" NVARCHAR2(100) NOT NULL,
    CONSTRAINT "MEDICAMENTOS_PK" PRIMARY KEY ("medicamento_id")
)';
END;
/

BEGIN 
EXECUTE IMMEDIATE 'CREATE TABLE 
"PETS" (
    "pet_id" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    "pet_nome" NVARCHAR2(50) NOT NULL,
    "pet_especie" NVARCHAR2(50) NOT NULL,
    "pet_raca" NVARCHAR2(50) NOT NULL,
    "pet_data_nascimento" TIMESTAMP(7) NOT NULL,
    "pet_peso" DECIMAL(5,2) NOT NULL,
    "dono_id" NUMBER(10) NOT NULL,
    CONSTRAINT "PETS_PK" PRIMARY KEY ("pet_id"),
    CONSTRAINT "PETS_DONOS_FK" FOREIGN KEY ("dono_id") REFERENCES "DONOS" ("dono_id") ON DELETE CASCADE
)';
END;
/

BEGIN 
EXECUTE IMMEDIATE 'CREATE TABLE 
"CONSULTAS" (
    "consulta_id" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    "consulta_tipo" NVARCHAR2(50) NOT NULL,
    "consulta_valor" DECIMAL(10,2) NOT NULL,
    "consulta_descricao" NVARCHAR2(500) NOT NULL,
    "consulta_status" NCHAR(1) NOT NULL,
    "consulta_data" TIMESTAMP(7) NOT NULL,
    "pet_id" NUMBER(10) NOT NULL,
    "funcionario_id" NUMBER(10) NOT NULL,
    CONSTRAINT "CONSULTAS_PK" PRIMARY KEY ("consulta_id"),
    CONSTRAINT "CK_CONSULTA_STATUS" CHECK (consulta_status IN ('A', 'C', 'R')),
    CONSTRAINT "CONSULTAS_FUNCIONARIOS_FK" FOREIGN KEY ("funcionario_id") REFERENCES "FUNCIONARIOS" ("funcionario_id") ON DELETE CASCADE,
    CONSTRAINT "CONSULTAS_PETS_FK" FOREIGN KEY ("pet_id") REFERENCES "PETS" ("pet_id") ON DELETE CASCADE
)';
END;
/

BEGIN 
EXECUTE IMMEDIATE 'CREATE TABLE 
"VACINAS" (
    "vacina_id" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    "vacina_nome" NVARCHAR2(50) NOT NULL,
    "vacina_data" TIMESTAMP(7) NOT NULL,
    "vacina_status" NCHAR(1) NOT NULL,
    "pet_id" NUMBER(10) NOT NULL,
    CONSTRAINT "VACINAS_PK" PRIMARY KEY ("vacina_id"),
    CONSTRAINT "CK_VACINA_STATUS" CHECK (vacina_status IN ('P', 'A')),
    CONSTRAINT "VACINAS_PETS_FK" FOREIGN KEY ("pet_id") REFERENCES "PETS" ("pet_id") ON DELETE CASCADE
)';
END;
/

BEGIN 
EXECUTE IMMEDIATE 'CREATE TABLE 
"CONSULTAS_MEDICAMENTOS" (
    "consulta_medicamento_id" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    "consulta_id" NUMBER(10) NOT NULL,
    "medicamento_id" NUMBER(10) NOT NULL,
    "cm_dosagem" NVARCHAR2(100) NOT NULL,
    CONSTRAINT "CONSULTAS_MEDICAMENTOS_PK" PRIMARY KEY ("consulta_medicamento_id"),
    CONSTRAINT "CM_CONSULTAS_FK" FOREIGN KEY ("consulta_id") REFERENCES "CONSULTAS" ("consulta_id") ON DELETE CASCADE,
    CONSTRAINT "CM_MEDICAMENTOS_FK" FOREIGN KEY ("medicamento_id") REFERENCES "MEDICAMENTOS" ("medicamento_id") ON DELETE CASCADE
)';
END;
/

CREATE INDEX "IX_CONSULTAS_funcionario_id" ON "CONSULTAS" ("funcionario_id")
/

CREATE INDEX "IX_CONSULTAS_pet_id" ON "CONSULTAS" ("pet_id")
/

CREATE INDEX "IX_CONSULTAS_MEDICAMENTOS_consulta_id" ON "CONSULTAS_MEDICAMENTOS" ("consulta_id")
/

CREATE INDEX "IX_CONSULTAS_MEDICAMENTOS_medicamento_id" ON "CONSULTAS_MEDICAMENTOS" ("medicamento_id")
/

CREATE UNIQUE INDEX "UQ_DONO_EMAIL" ON "DONOS" ("dono_email")
/

CREATE UNIQUE INDEX "UQ_FUNC_EMAIL" ON "FUNCIONARIOS" ("funcionario_email")
/

CREATE INDEX "IX_PETS_dono_id" ON "PETS" ("dono_id")
/

CREATE INDEX "IX_VACINAS_pet_id" ON "VACINAS" ("pet_id")
/
